# List of relevant features and axis names.
identifier_features = [
    ('Date', 'Date'),
    ('Hour', 'Hour'),
    ('VarFilter_WTP_GPS1_lat', 'Latitude'),
    ('VarFilter_WTP_GPS1_long', 'Longitude')
]
fiber_optics_structure_features = [
    ('Max_1s_FBM_P_laft_0_11','Max_Port_Front_Beam_A1'),
    ('Max_1s_FBM_P_laft_0_21','Max_Port_Front_Beam_B1'),
    ('Max_1s_FBM_P_laft_0_31','Max_Port_Front_Beam_C1'),
    ('Max_1s_FBM_P_laft_0_41','Max_Port_Front_Beam_D1'),
    ('Max_1s_FBM_P_lfwd_0_14','Max_Port_Front_Beam_A4'),
    ('Max_1s_FBM_P_lfwd_0_24','Max_Port_Front_Beam_B4'),
    ('Max_1s_FBM_P_lfwd_0_34','Max_Port_Front_Beam_C4'),
    ('Max_1s_FBM_P_lfwd_0_44','Max_Port_Front_Beam_D4'),
    ('Max_1s_FBM_P_uaft_0_12','Max_Port_Front_Beam_A2'),
    ('Max_1s_FBM_P_uaft_0_22','Max_Port_Front_Beam_B2'),
    ('Max_1s_FBM_P_uaft_0_32','Max_Port_Front_Beam_C2'),
    ('Max_1s_FBM_P_uaft_0_42','Max_Port_Front_Beam_D2'),
    ('Max_1s_FBM_P_ufwd_0_13','Max_Port_Front_Beam_A3'),
    ('Max_1s_FBM_P_ufwd_0_23','Max_Port_Front_Beam_B3'),
    ('Max_1s_FBM_P_ufwd_0_33','Max_Port_Front_Beam_C3'),
    ('Max_1s_FBM_P_ufwd_0_43','Max_Port_Front_Beam_D3'),
    ('Max_1s_FBM_S_laft_0_11','Max_Starboard_Front_Beam_A1'),
    ('Max_1s_FBM_S_laft_0_21','Max_Starboard_Front_Beam_B1'),
    ('Max_1s_FBM_S_laft_0_31','Max_Starboard_Front_Beam_C1'),
    ('Max_1s_FBM_S_laft_0_41','Max_Starboard_Front_Beam_D1'),
    ('Max_1s_FBM_S_lfwd_0_14','Max_Starboard_Front_Beam_A4'),
    ('Max_1s_FBM_S_lfwd_0_24','Max_Starboard_Front_Beam_B4'),
    ('Max_1s_FBM_S_lfwd_0_34','Max_Starboard_Front_Beam_C4'),
    ('Max_1s_FBM_S_lfwd_0_44','Max_Starboard_Front_Beam_D4'),
    ('Max_1s_FBM_S_uaft_0_12','Max_Starboard_Front_Beam_A2'),
    ('Max_1s_FBM_S_uaft_0_22','Max_Starboard_Front_Beam_B2'),
    ('Max_1s_FBM_S_uaft_0_32','Max_Starboard_Front_Beam_C2'),
    ('Max_1s_FBM_S_uaft_0_42','Max_Starboard_Front_Beam_D2'),
    ('Max_1s_FBM_S_ufwd_0_13','Max_Starboard_Front_Beam_A3'),
    ('Max_1s_FBM_S_ufwd_0_23','Max_Starboard_Front_Beam_B3'),
    ('Max_1s_FBM_S_ufwd_0_33','Max_Starboard_Front_Beam_C3'),
    ('Max_1s_FBM_S_ufwd_0_43','Max_Starboard_Front_Beam_D3'),
    ('Max_1s_HUL_C_lport_0_11','Max_Center_Hull_11'),
    ('Max_1s_HUL_C_lport_0_21','Max_Center_Hull_21'),
    ('Max_1s_HUL_C_lstbd_0_14','Max_Center_Hull_14'),
    ('Max_1s_HUL_C_lstbd_0_24','Max_Center_Hull_24'),
    ('Max_1s_HUL_C_uport_0_12','Max_Center_Hull_12'),
    ('Max_1s_HUL_C_uport_0_22','Max_Center_Hull_22'),
    ('Max_1s_HUL_C_ustbd_0_13','Max_Center_Hull_13'),
    ('Max_1s_HUL_C_ustbd_0_23','Max_Center_Hull_23'),
    ('Max_1s_HUL_P_lport_0_11','Max_Port_Hull_11'),
    ('Max_1s_HUL_P_lport_0_21','Max_Port_Hull_21'),
    ('Max_1s_HUL_P_lstbd_0_14','Max_Port_Hull_14'),
    ('Max_1s_HUL_P_lstbd_0_24','Max_Port_Hull_24'),
    ('Max_1s_HUL_P_uport_0_12','Max_Port_Hull_12'),
    ('Max_1s_HUL_P_uport_0_22','Max_Port_Hull_22'),
    ('Max_1s_HUL_P_ustbd_0_13','Max_Port_Hull_13'),
    ('Max_1s_HUL_P_ustbd_0_23','Max_Port_Hull_23'),
    ('Max_1s_HUL_S_lport_0_11','Max_Starboard_Hull_11'),
    ('Max_1s_HUL_S_lport_U_21','Max_Starboard_Hull_21'),
    ('Max_1s_HUL_S_lstbd_0_14','Max_Starboard_Hull_14'),
    ('Max_1s_HUL_S_lstbd_0_24','Max_Starboard_Hull_24'),
    ('Max_1s_HUL_S_uport_0_12','Max_Starboard_Hull_12'),
    ('Max_1s_HUL_S_uport_U_22','Max_Starboard_Hull_22'),
    ('Max_1s_HUL_S_ustbd_0_13','Max_Starboard_Hull_13'),
    ('Max_1s_HUL_S_ustbd_0_23','Max_Starboard_Hull_23'),
    ('Min_1s_FBM_P_laft_0_11','Min_Port_Front_Beam_A1'),
    ('Min_1s_FBM_P_laft_0_21','Min_Port_Front_Beam_B1'),
    ('Min_1s_FBM_P_laft_0_31','Min_Port_Front_Beam_C1'),
    ('Min_1s_FBM_P_laft_0_41','Min_Port_Front_Beam_D1'),
    ('Min_1s_FBM_P_lfwd_0_14','Min_Port_Front_Beam_A4'),
    ('Min_1s_FBM_P_lfwd_0_24','Min_Port_Front_Beam_B4'),
    ('Min_1s_FBM_P_lfwd_0_34','Min_Port_Front_Beam_C4'),
    ('Min_1s_FBM_P_lfwd_0_44','Min_Port_Front_Beam_D4'),
    ('Min_1s_FBM_P_uaft_0_12','Min_Port_Front_Beam_A2'),
    ('Min_1s_FBM_P_uaft_0_22','Min_Port_Front_Beam_B2'),
    ('Min_1s_FBM_P_uaft_0_32','Min_Port_Front_Beam_C2'),
    ('Min_1s_FBM_P_uaft_0_42','Min_Port_Front_Beam_D2'),
    ('Min_1s_FBM_P_ufwd_0_13','Min_Port_Front_Beam_A3'),
    ('Min_1s_FBM_P_ufwd_0_23','Min_Port_Front_Beam_B3'),
    ('Min_1s_FBM_P_ufwd_0_33','Min_Port_Front_Beam_C3'),
    ('Min_1s_FBM_P_ufwd_0_43','Min_Port_Front_Beam_D3'),
    ('Min_1s_FBM_S_laft_0_11','Min_Starboard_Front_Beam_A1'),
    ('Min_1s_FBM_S_laft_0_21','Min_Starboard_Front_Beam_B1'),
    ('Min_1s_FBM_S_laft_0_31','Min_Starboard_Front_Beam_C1'),
    ('Min_1s_FBM_S_laft_0_41','Min_Starboard_Front_Beam_D1'),
    ('Min_1s_FBM_S_lfwd_0_14','Min_Starboard_Front_Beam_A4'),
    ('Min_1s_FBM_S_lfwd_0_24','Min_Starboard_Front_Beam_B4'),
    ('Min_1s_FBM_S_lfwd_0_34','Min_Starboard_Front_Beam_C4'),
    ('Min_1s_FBM_S_lfwd_0_44','Min_Starboard_Front_Beam_D4'),
    ('Min_1s_FBM_S_uaft_0_12','Min_Starboard_Front_Beam_A2'),
    ('Min_1s_FBM_S_uaft_0_22','Min_Starboard_Front_Beam_B2'),
    ('Min_1s_FBM_S_uaft_0_32','Min_Starboard_Front_Beam_C2'),
    ('Min_1s_FBM_S_uaft_0_42','Min_Starboard_Front_Beam_D2'),
    ('Min_1s_FBM_S_ufwd_0_13','Min_Starboard_Front_Beam_A3'),
    ('Min_1s_FBM_S_ufwd_0_23','Min_Starboard_Front_Beam_B3'),
    ('Min_1s_FBM_S_ufwd_0_33','Min_Starboard_Front_Beam_C3'),
    ('Min_1s_FBM_S_ufwd_0_43','Min_Starboard_Front_Beam_D3'),
    ('Min_1s_HUL_C_lport_0_11','Min_Center_Hull_11'),
    ('Min_1s_HUL_C_lport_0_21','Min_Center_Hull_21'),
    ('Min_1s_HUL_C_lstbd_0_14','Min_Center_Hull_14'),
    ('Min_1s_HUL_C_lstbd_0_24','Min_Center_Hull_24'),
    ('Min_1s_HUL_C_uport_0_12','Min_Center_Hull_12'),
    ('Min_1s_HUL_C_uport_0_22','Min_Center_Hull_22'),
    ('Min_1s_HUL_C_ustbd_0_13','Min_Center_Hull_13'),
    ('Min_1s_HUL_C_ustbd_0_23','Min_Center_Hull_23'),
    ('Min_1s_HUL_P_lport_0_11','Min_Port_Hull_11'),
    ('Min_1s_HUL_P_lport_0_21','Min_Port_Hull_21'),
    ('Min_1s_HUL_P_lstbd_0_14','Min_Port_Hull_14'),
    ('Min_1s_HUL_P_lstbd_0_24','Min_Port_Hull_24'),
    ('Min_1s_HUL_P_uport_0_12','Min_Port_Hull_12'),
    ('Min_1s_HUL_P_uport_0_22','Min_Port_Hull_22'),
    ('Min_1s_HUL_P_ustbd_0_13','Min_Port_Hull_13'),
    ('Min_1s_HUL_P_ustbd_0_23','Min_Port_Hull_23'),
    ('Min_1s_HUL_S_lport_0_11','Min_Starboard_Hull_11'),
    ('Min_1s_HUL_S_lport_U_21','Min_Starboard_Hull_21'),
    ('Min_1s_HUL_S_lstbd_0_14','Min_Starboard_Hull_14'),
    ('Min_1s_HUL_S_lstbd_0_24','Min_Starboard_Hull_24'),
    ('Min_1s_HUL_S_uport_0_12','Min_Starboard_Hull_12'),
    ('Min_1s_HUL_S_uport_U_22','Min_Starboard_Hull_22'),
    ('Min_1s_HUL_S_ustbd_0_13','Min_Starboard_Hull_13'),
    ('Min_1s_HUL_S_ustbd_0_23','Min_Starboard_Hull_23')
  
]
fiber_optics_appendix_features = [
    
    ('Max_1s_Foil_B_P_1_i_0_1','Port_Foil_Max_Deformation_in_1'),
    ('Max_1s_Foil_B_P_1_i_0_2','Port_Foil_Max_Deformation_in_2'),
    ('Max_1s_Foil_B_P_1_i_0_3','Port_Foil_Max_Deformation_in_3'),
    ('Max_1s_Foil_B_P_1_i_0_4','Port_Foil_Max_Deformation_in_4'),
    ('Max_1s_Foil_B_P_1_i_0_5','Port_Foil_Max_Deformation_in_5'),
    ('Max_1s_Foil_B_P_1_i_0_6','Port_Foil_Max_Deformation_in_6'),
    ('Max_1s_Foil_B_P_1_i_0_7','Port_Foil_Max_Deformation_in_7'),
    ('Max_1s_Foil_B_P_1_i_0_8','Port_Foil_Max_Deformation_in_8'),
    ('Max_1s_Foil_B_P_1_o_0_11','Port_Foil_Max_Deformation_out_1'),
    ('Max_1s_Foil_B_P_1_o_0_2','Port_Foil_Max_Deformation_out_2'),
    ('Max_1s_Foil_B_P_1_o_0_3','Port_Foil_Max_Deformation_out_3'),
    ('Max_1s_Foil_B_P_1_o_0_4','Port_Foil_Max_Deformation_out_4'),
    ('Max_1s_Foil_B_P_1_o_0_53','Port_Foil_Max_Deformation_out_5'),
    ('Max_1s_Foil_B_P_1_o_0_61','Port_Foil_Max_Deformation_out_6'),
    ('Max_1s_Foil_B_P_1_o_0_7','Port_Foil_Max_Deformation_out_7'),
    ('Max_1s_Foil_B_P_1_o_0_8','Port_Foil_Max_Deformation_out_8'),
    ('Max_1s_Foil_B_S_1_i_0_1','Starboard_Foil_Max_Deformation_in_1'),
    ('Max_1s_Foil_B_S_1_i_0_2','Starboard_Foil_Max_Deformation_in_2'),
    ('Max_1s_Foil_B_S_1_i_0_3','Starboard_Foil_Max_Deformation_in_3'),
    ('Max_1s_Foil_B_S_1_i_0_4','Starboard_Foil_Max_Deformation_in_4'),
    ('Max_1s_Foil_B_S_1_i_0_5','Starboard_Foil_Max_Deformation_in_5'),
    ('Max_1s_Foil_B_S_1_i_0_6','Starboard_Foil_Max_Deformation_in_6'),
    ('Max_1s_Foil_B_S_1_i_0_7','Starboard_Foil_Max_Deformation_in_7'),
    ('Max_1s_Foil_B_S_1_i_0_8','Starboard_Foil_Max_Deformation_in_8'),
    ('Max_1s_Foil_B_S_1_o_0_11','Starboard_Foil_Max_Deformation_out_1'),
    ('Max_1s_Foil_B_S_1_o_0_2','Starboard_Foil_Max_Deformation_out_2'),
    ('Max_1s_Foil_B_S_1_o_0_3','Starboard_Foil_Max_Deformation_out_3'),
    ('Max_1s_Foil_B_S_1_o_0_4','Starboard_Foil_Max_Deformation_out_4'),
    ('Max_1s_Foil_RUD_C_1_e_0_P1','Central_Rudder_Max_Deformation_Port_1'),
    ('Max_1s_Foil_RUD_C_1_e_0_P2','Central_Rudder_Max_Deformation_Port_2'),
    ('Max_1s_Foil_RUD_C_1_e_0_S1','Central_Rudder_Max_Deformation_Starboard_1'),
    ('Max_1s_Foil_RUD_C_1_e_0_S2','Central_Rudder_Max_Deformation_Starboard_2'),
    ('Min_1s_Foil_B_P_1_i_0_1','Port_Foil_Min_Deformation_in_1'),
    ('Min_1s_Foil_B_P_1_i_0_2','Port_Foil_Min_Deformation_in_2'),
    ('Min_1s_Foil_B_P_1_i_0_3','Port_Foil_Min_Deformation_in_3'),
    ('Min_1s_Foil_B_P_1_i_0_4','Port_Foil_Min_Deformation_in_4'),
    ('Min_1s_Foil_B_P_1_i_0_5','Port_Foil_Min_Deformation_in_5'),
    ('Min_1s_Foil_B_P_1_i_0_6','Port_Foil_Min_Deformation_in_6'),
    ('Min_1s_Foil_B_P_1_i_0_7','Port_Foil_Min_Deformation_in_7'),
    ('Min_1s_Foil_B_P_1_i_0_8','Port_Foil_Min_Deformation_in_8'),
    ('Min_1s_Foil_B_P_1_o_0_11','Port_Foil_Min_Deformation_out_1'),
    ('Min_1s_Foil_B_P_1_o_0_2','Port_Foil_Min_Deformation_out_2'),
    ('Min_1s_Foil_B_P_1_o_0_3','Port_Foil_Min_Deformation_out_3'),
    ('Min_1s_Foil_B_P_1_o_0_4','Port_Foil_Min_Deformation_out_4'),
    ('Min_1s_Foil_B_P_1_o_0_53','Port_Foil_Min_Deformation_out_5'),
    ('Min_1s_Foil_B_P_1_o_0_61','Port_Foil_Min_Deformation_out_6'),
    ('Min_1s_Foil_B_P_1_o_0_7','Port_Foil_Min_Deformation_out_7'),
    ('Min_1s_Foil_B_P_1_o_0_8','Port_Foil_Min_Deformation_out_8'),
    ('Min_1s_Foil_B_S_1_i_0_1','Starboard_Foil_Min_Deformation_in_1'),
    ('Min_1s_Foil_B_S_1_i_0_2','Starboard_Foil_Min_Deformation_in_2'),
    ('Min_1s_Foil_B_S_1_i_0_3','Starboard_Foil_Min_Deformation_in_3'),
    ('Min_1s_Foil_B_S_1_i_0_4','Starboard_Foil_Min_Deformation_in_4'),
    ('Min_1s_Foil_B_S_1_i_0_5','Starboard_Foil_Min_Deformation_in_5'),
    ('Min_1s_Foil_B_S_1_i_0_6','Starboard_Foil_Min_Deformation_in_6'),
    ('Min_1s_Foil_B_S_1_i_0_7','Starboard_Foil_Min_Deformation_in_7'),
    ('Min_1s_Foil_B_S_1_i_0_8','Starboard_Foil_Min_Deformation_in_8'),
    ('Min_1s_Foil_B_S_1_o_0_11','Starboard_Foil_Min_Deformation_out_1'),
    ('Min_1s_Foil_B_S_1_o_0_2','Starboard_Foil_Min_Deformation_out_2'),
    ('Min_1s_Foil_B_S_1_o_0_3','Starboard_Foil_Min_Deformation_out_3'),
    ('Min_1s_Foil_B_S_1_o_0_4','Starboard_Foil_Min_Deformation_out_4'),
    ('Min_1s_Foil_RUD_C_1_e_0_P1','Central_Rudder_Min_Deformation_Port_1'),
    ('Min_1s_Foil_RUD_C_1_e_0_P2','Central_Rudder_Min_Deformation_Port_2'),
    ('Min_1s_Foil_RUD_C_1_e_0_S1','Central_Rudder_Min_Deformation_Starboard_1'),
    ('Min_1s_Foil_RUD_C_1_e_0_S2','Central_Rudder_Min_Deformation_Starboard_2') 
]
other_sensor_features = [
    ('IxBlue_Heading', 'Heading(cap)'),
    ('IxBlue_Heave', 'Heave(translation_en_hauteur)'),
    ('IxBlue_HeaveAccel', 'Heave_Accel(vitesse_translation_en_hauteur'),
    ('IxBlue_Pitch', 'Pitch(tangage_vers_avant)'),
    ('IxBlue_PitchRate', 'Pitch_Rate(vitesse_tangage_vers_avant)'),
    ('IxBlue_Roll', 'Roll(rouli)'),
    ('IxBlue_RollRate', 'Roll_Rate(vitesse_rouli)'),
    ('IxBlue_SurgeAccel', 'Surge_Accel(acceleration)'),
    ('IxBlue_SwayAccel', 'Sway_Accel(acceleration_en_Y)'),
    ('IxBlue_YawRate', 'Yaw_Rate(vitesse_rotation)'),
    ('RM_RM', 'Righting_Moment'),
    ('VarFilter_sirius_b2_ 1', 'Reefing2(Prise_2ris)'),
    ('VarFilter_sirius_b2_ 2', 'Reefing1(Prise_1ris)'),
    ('VarFilter_sirius_b2_ 3', 'Mainsail_Full'),
    ('VarFilter_WTP_Mainsheet_Load', 'Mainsail_Load'),
    ('VarFilter_WTP_Forestay_0_Load', 'Forestay_Load_J0(charge_etai_J0'),
    ('VarFilter_WTP_Forestay_1_Load', 'Forestay_Load_J1(charge_etai_J1'),
    ('VarFilter_WTP_Forestay_2_Load', 'Forestay_Load_J2(charge_etai_J2'),
    ('VarFilter_WTP_MastRot', 'Mast_Rotation_Angle'),
    ('VarFilter_WTP_CBoard_Elevator_angle', 'Board_Elevator_Angle_Center'),
    ('VarFilter_WTP_CBoard_Trimmer_angle_norm', 'Board_Trimmer_Angle_Center'),
    ('VarFilter_WTP_Cboard_Extension', 'Board_Extension_Center'),
    ('VarFilter_WTP_Cboard_Load', 'Board_Load_Center'),
    ('VarFilter_WTP_Foil_Prt_Extension', 'Board_Extension_Port'),
    ('VarFilter_WTP_Foil_Prt_Rake', 'Board_Rake_Port'),
    ('VarFilter_WTP_Foil_Stb_Extension', 'Board_Extension_Starboard'),
    ('VarFilter_WTP_Foil_Stb_Rake', 'Board_Rake_Starboard'),
    ('VarFilter_WTP_Rudder_Angle_CC', 'Rudder_Angle_Center'),
    ('VarFilter_WTP_Rudder_CC_Elevator_angle', 'Rudder_Elevator_Angle_Center'),
    ('VarFilter_WTP_Rudder_Angle_Prt', 'Rudder_Angle_Port'),
    ('VarFilter_WTP_Rudder_Prt_Elevator_angle', 'Rudder_Elevator_Angle_Port'),
    ('VarFilter_WTP_Rudder_Prt_Load_I', 'Rudder_Inside_Load_Port'),
    ('VarFilter_WTP_Rudder_Prt_Load_O', 'Rudder_Outside_Load_Port'),
    ('VarFilter_WTP_Rudder_Angle_Stb', 'Rudder_Angle_Starboard'),
    ('VarFilter_WTP_Rudder_Stb_Elevator_angle', 'Rudder_Elevator_Angle_Starboard'),
    ('VarFilter_WTP_Rudder_Stb_Load_I', 'Rudder_Inside_Load_Starboard'),
    ('VarFilter_WTP_Rudder_Stb_Load_O', 'Rudder_Outside_Load_Starboard'),
    ('VarFilter_WTP_Shroud_Prt_Load', 'Shroud_Load_Port'),
    ('VarFilter_WTP_Shroud_Stb_Load', 'Shroud_Load_Starboard')
]
wind_features = [
    ('VarFilter_WTP_TW_angle', 'Wind_Angle'),
    ('VarFilter_WTP_TW_speed', 'Wind_Speed')
]
boat_speed_feature = ('VarFilter_WTP_SelBoatSpd', 'Boat_Speed')
bins_axis_names = ['Wind Angle (˚)', 'Wind Speed (knots)']
boxplot_axis_name = 'Boat Speed (knots)'
coc_feature_name = 'Feature'

# Regular expressions.
feature_regex = r'.*{}.*'
bin_dimensions_regex = r'[+-]?\d+'

# Other features.
statistics_features = ['Feature', 'Corr']
